"""
SBATCH Header Builder for SLURM job scripts.

Generates the shebang, header comment, and #SBATCH directives
for SLURM job submission.
"""

from .base import BaseBuilder


class SBatchHeaderBuilder(BaseBuilder):
    """Build the SBATCH header section of a SLURM job script.

    This builder generates:
    1. Shebang (#!/bin/bash)
    2. Descriptive header comment block
    3. All #SBATCH directives for resource allocation

    Example output:
        #!/bin/bash
        # =============================================================================
        # Qwen2.5-0.5B GRPO Training on OpenMathInstruct-2
        # Auto-generated by SLURM Job Generator
        # =============================================================================

        #SBATCH --job-name=qwen-grpo-openmath
        #SBATCH --account=def-maxwl_gpu
        ...
    """

    def build(self) -> str:
        """Build the complete SBATCH header section.

        Returns:
            The shebang, header comment, and SBATCH directives.
        """
        sections = [
            self._shebang_and_header(),
            self._sbatch_directives(),
        ]
        return "\n".join(sections)

    def _shebang_and_header(self) -> str:
        """Generate the shebang and descriptive header comment.

        Returns:
            Shebang and header block as a string.
        """
        return f"""#!/bin/bash
# =============================================================================
# {self.model_short_name} {self.method_upper} Training on {self.dataset_short_name}
# Auto-generated by SLURM Job Generator
# =============================================================================
"""

    def _sbatch_directives(self) -> str:
        """Generate all #SBATCH directives.

        Returns:
            All SBATCH directives as a multi-line string.
        """
        c = self.config  # Shorthand for readability

        directives = [
            f"#SBATCH --job-name={c.job_name}",
            f"#SBATCH --account={c.account}",
            f"#SBATCH --time={c.time_limit}",
            "#SBATCH --nodes=1",
            "#SBATCH --ntasks-per-node=1",
            f"#SBATCH --cpus-per-task={c.cpus}",
            f"#SBATCH --mem={c.memory}",
            f"#SBATCH --gres={c.gres}",
            f"#SBATCH --partition={c.partition}",
            "#SBATCH --output=logs/%x-%j.out",
            "#SBATCH --error=logs/%x-%j.err",
            "#SBATCH --mail-type=BEGIN,END,FAIL",
        ]

        return "\n".join(directives)
