#!/bin/bash
# =============================================================================
# LFM2.5-1.2B-Instruct GRPO Training on NuminaMath-CoT
# Auto-generated by SLURM Job Generator
# =============================================================================

#SBATCH --job-name=lfm2.5-1.2b-instruct-grpo-numinamath-cot
#SBATCH --account=def-maxwl_gpu
#SBATCH --time=0-02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --gres=gpu:nvidia_h100_80gb_hbm3_3g.40gb:1
#SBATCH --partition=gpubase_bygpu_b2
#SBATCH --output=logs/%x-%j.out
#SBATCH --error=logs/%x-%j.err
#SBATCH --mail-type=BEGIN,END,FAIL
# =============================================================================
# Configuration
# =============================================================================
MODEL_NAME='LiquidAI/LFM2.5-1.2B-Instruct'
DATASET_NAME='AI-MO/NuminaMath-CoT'

# Sample size configuration (for model naming when using streaming)
MAX_SAMPLES=100
SAMPLE_SIZE_LABEL="smoke-100"

HUB_MODEL_ID='ermiaazarkhalili/LFM2.5-1.2B-Instruct-GRPO-NuminaMath-10K'
GGUF_REPO_ID='ermiaazarkhalili/LFM2.5-1.2B-Instruct-GRPO-NuminaMath-10K-GGUF'

# Training parameters (small model config)
BATCH_SIZE=2
GRAD_ACCUM=8
LEARNING_RATE=1e-06
NUM_EPOCHS=1
LORA_R=16
LORA_ALPHA=32
MAX_COMPLETION_LENGTH=4096
MAX_PROMPT_LENGTH=512
NUM_GENERATIONS=4
REWARD_TYPE='combined'


# =============================================================================
# Environment Setup
# =============================================================================
echo "=========================================="
echo "Job: $SLURM_JOB_NAME (ID: $SLURM_JOB_ID)"
echo "=========================================="
echo "Node: $SLURMD_NODENAME"
echo "Start time: $(date)"
echo ""

mkdir -p logs

# Load modules
module load gcc arrow python/3.11.5

# Activate virtual environment
source /scratch/ermia/venvs/hf_env/bin/activate

# Set environment variables
export SCRATCH=${SCRATCH:-/scratch/$USER}
export HF_HOME=$SCRATCH/.cache/huggingface
export TRANSFORMERS_CACHE=$HF_HOME/hub
export OUTPUT_DIR="$SCRATCH/outputs/lfm2.5-1.2b-instruct-grpo-numinamath-cot-$SLURM_JOB_ID"

# Log MIG status for debugging (training script handles pin_memory auto-detection)
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
if [[ "$CUDA_VISIBLE_DEVICES" == MIG* ]]; then
    echo "MIG device detected — training script will auto-handle pin_memory and bf16"
fi

# Load HF token
if [[ -f "/project/6014832/ermia/HF-TRL/.env" ]]; then
    while IFS='=' read -r key value; do
        # Skip comments and empty lines
        [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
        # Remove surrounding quotes from value
        value="${value%\"}"; value="${value#\"}"
        value="${value%\'}"; value="${value#\'}"
        export "$key=$value"
    done < "/project/6014832/ermia/HF-TRL/.env"
fi

mkdir -p $OUTPUT_DIR

echo ""
echo "Configuration:"
echo "  Model: $MODEL_NAME"
echo "  Dataset: $DATASET_NAME"
echo "  Hub Model ID: $HUB_MODEL_ID"
echo "  Batch Size: $BATCH_SIZE"
echo "  Gradient Accumulation: $GRAD_ACCUM"
echo "  Effective Batch Size: $((BATCH_SIZE * GRAD_ACCUM))"
echo "  Num Generations: $NUM_GENERATIONS"
echo "  Reward Type: $REWARD_TYPE"
echo "  LoRA Rank: $LORA_R"
echo "  Output Dir: $OUTPUT_DIR"
echo ""

# =============================================================================
# Phase 1: Training
# =============================================================================
echo "=========================================="
echo "Phase 1: GRPO Training"
echo "=========================================="

PYTHONUNBUFFERED=1 python /project/6014832/ermia/HF-TRL/.claude/skills/slurm-model-trainer/scripts/train_grpo.py \
    --model_name_or_path $MODEL_NAME \
    --dataset_name $DATASET_NAME \
    --output_dir $OUTPUT_DIR \
    --num_train_epochs $NUM_EPOCHS \
    --per_device_train_batch_size $BATCH_SIZE \
    --gradient_accumulation_steps $GRAD_ACCUM \
    --learning_rate $LEARNING_RATE \
    --bf16 \
    --gradient_checkpointing \
    --lora_r $LORA_R \
    --lora_alpha $LORA_ALPHA \
    --lora_dropout 0.05 \
    --save_strategy steps \
    --save_steps 500 \
    --save_total_limit 3 \
    --logging_steps 10 \
    --hub_model_id $HUB_MODEL_ID \
    --hub_strategy end \
    --report_to trackio \
    --project "lfm2.5-1.2b-instruct-grpo-numinamath" \
    --run_name "lfm2.5-1.2b-instruct-grpo-numinamath-cot-$SLURM_JOB_ID" \
    --streaming \
    --max_samples 100 \
    --max_completion_length $MAX_COMPLETION_LENGTH \
    --max_prompt_length $MAX_PROMPT_LENGTH \
    --num_generations $NUM_GENERATIONS \
    --reward_type $REWARD_TYPE

TRAIN_EXIT_CODE=$?

if [[ $TRAIN_EXIT_CODE -ne 0 ]]; then
    echo "ERROR: Training failed with exit code $TRAIN_EXIT_CODE"
    exit $TRAIN_EXIT_CODE
fi

echo "Training completed successfully!"

# =============================================================================
# Phase 2: Generate Model Card
# =============================================================================
echo ""
echo "=========================================="
echo "Phase 2: Generating Model Card"
echo "=========================================="

PYTHONUNBUFFERED=1 python /project/6014832/ermia/HF-TRL/.claude/skills/slurm-model-trainer/scripts/generate_model_card.py \
    --model_name "LFM2.5-1.2B-Instruct-GRPO-NuminaMath-10K" \
    --base_model "$MODEL_NAME" \
    --dataset "$DATASET_NAME" \
    --training_method GRPO \
    --author ermiaazarkhalili \
    --license cc-by-nc-4.0 \
    --learning_rate $LEARNING_RATE \
    --batch_size $BATCH_SIZE \
    --epochs $NUM_EPOCHS \
    --max_length $MAX_COMPLETION_LENGTH \
    --lora_r $LORA_R \
    --lora_alpha $LORA_ALPHA \
    --hardware "NVIDIA H100 MIG" \
    --output_dir $OUTPUT_DIR/model_card

# Push model card to Hub
PYTHONUNBUFFERED=1 python -c "
import os
from huggingface_hub import HfApi
api = HfApi()
output_dir = os.environ['OUTPUT_DIR']
hub_model_id = os.environ.get('HUB_MODEL_ID', '')
if not hub_model_id:
    print('WARNING: HUB_MODEL_ID not set, skipping model card upload')
else:
    card_path = os.path.join(output_dir, 'model_card', 'README.md')
    if not os.path.exists(card_path):
        print(f'WARNING: Model card not found at {card_path}')
    else:
        api.upload_file(
            path_or_fileobj=card_path,
            path_in_repo='README.md',
            repo_id=hub_model_id,
        )
        print(f'Model card uploaded to {hub_model_id}')
"

# =============================================================================
# Phase 3: Evaluation (Math benchmarks)
# =============================================================================
echo ""
echo "=========================================="
echo "Phase 3: Evaluation (GSM8K, MATH)"
echo "=========================================="

pip install -q lm-eval

PYTHONUNBUFFERED=1 python -c "
import os
import subprocess

model_id = os.environ.get('HUB_MODEL_ID', '')
output_dir = os.path.join(os.environ['OUTPUT_DIR'], 'eval_results')

if not model_id:
    print('WARNING: HUB_MODEL_ID not set, skipping evaluation')
else:
    cmd = [
        'lm_eval',
        '--model', 'hf',
        '--model_args', f'pretrained={model_id},trust_remote_code=True',
        '--tasks', 'gsm8k,minerva_math',
        '--batch_size', 'auto',
        '--output_path', output_dir,
        '--log_samples',
    ]

    cmd_str = ' '.join(cmd)
    print(f'Running: {cmd_str}')
    result = subprocess.run(cmd, capture_output=True, text=True)
    print(result.stdout)
    if result.returncode != 0:
        print(f'Warning: Evaluation had issues: {result.stderr}')
"

# =============================================================================
# Phase 4: GGUF Conversion
# =============================================================================
echo ""
echo "=========================================="
echo "Phase 4: GGUF Conversion (Q4_K_M)"
echo "=========================================="

PYTHONUNBUFFERED=1 python /project/6014832/ermia/HF-TRL/.claude/skills/slurm-model-trainer/scripts/convert_gguf.py \
    --model $HUB_MODEL_ID \
    --base_model $MODEL_NAME \
    --output_repo $GGUF_REPO_ID \
    --quantizations "Q4_K_M,Q5_K_M,Q8_0" \
    --output_dir $OUTPUT_DIR/gguf

GGUF_EXIT_CODE=$?

if [[ $GGUF_EXIT_CODE -ne 0 ]]; then
    echo "WARNING: GGUF conversion had issues (exit code $GGUF_EXIT_CODE)"
else
    echo "GGUF conversion completed successfully!"
fi

# =============================================================================
# Summary
# =============================================================================
echo ""
echo "=========================================="
echo "Pipeline Complete!"
echo "=========================================="
echo "End time: $(date)"
echo ""
echo "Outputs:"
echo "  Training Output: $OUTPUT_DIR"
echo "  Model on Hub: https://huggingface.co/$HUB_MODEL_ID"
echo "  GGUF on Hub: https://huggingface.co/$GGUF_REPO_ID"
echo "  Eval Results: $OUTPUT_DIR/eval_results"
echo ""
echo "To use with Ollama:"
echo "  ollama pull hf.co/$GGUF_REPO_ID:Q4_K_M"
echo ""
